Add new book
ProductDock/rbc-library-ui pull request #145
Opened 2024-02-21 12:15 UTC by NenadJeckovic

Added new book form to admin books page with success and failure response messages. Tests included in AdminBooksPage tests.

2024-02-23 14:33 UTC, ssukovic requested changes
Two additional points:

- Some error handling should be added while we're moving these functionalities, currently when api for adding new books fails nothing happens. In the file NewBookForm similar to onSuccessCallback create onFailureCallback which doesn't hide the form and displays a failure message to the user "Error when adding a new book. Please try again later". 
- It would be helpful and a good practice if you added descriptions to your PRs, just simple outline explaining what you did and how to test it, so reviewers can see at a glance what's going on without having to look for the related ticket.

2024-02-23 14:33 UTC, ssukovic commented on src/pages/AdminBooksPage/AdminBooksPage.test.tsx
> +});
You should add one test that shows what happens when button is clicked and goes through the whole flow, fills the form, submits the book and checks if success notification shows up. 
NewBookForm.test covers only the form, we should also test the integration and the whole flow.

2024-02-29 09:24 UTC, ssukovic approved these changes
Great job 🎉

2024-02-29 09:30 UTC, ssukovic commented on src/components/Notification/index.tsx
> +        <>{warning ? <WarningScreen /> : <SuccessScreen />}</>
Good catch, I forgot about the mobile screen 😄

2024-02-29 09:35 UTC, dusanpetrovicpd approved these changes

2024-03-01 08:20 UTC, merged